// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdmmbrquclvqxkjndngl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkbW1icnF1Y2x2cXhram5kbmdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NzcwMTQsImV4cCI6MjA2NTQ1MzAxNH0.Byl21kM7apG_FaWmo27unl0OlTKS75v_sJ6PmP9_-eE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);